### ISSUE TITLE
code separated by semi-colon

### ISSUE THREAD

**Issue by stla** [ramnathv/poirot#28]
Is it expected ? Knitting with RStudio generates two blocks for the two results.
![capture](https://cloud.githubusercontent.com/assets/4466543/2687571/eab2f7a0-c25e-11e3-98c0-cf89e92211f1.PNG)

**Comment by ramnathv** [comment]
Slidify lets `knitr` handle conversion of `Rmd` to `md`. So it should behave exactly as `knitr` will behave. Can you check what you get by knitting the `Rmd` file directly in RStudio without Slidify?

**Comment by stla** [comment]
That's highly strange. I have just tried the following `Rmd` file:

```
---
title: temp
--- &lead

hello 

[backticks]{r}
2+2; 3+3
[backticks]
```

and it generates the same output as `knitr`:
![capture](https://cloud.githubusercontent.com/assets/4466543/2688018/5555dda6-c27e-11e3-9b5d-a4a0e6fdfef7.PNG)

So, how did I get the previous output ???????? Isn't there an option declared somewhere ?

**Comment by stla** [comment]
Ooohh I see: this is due to the `tidy` option !

**Comment by ramnathv** [comment]
Yes, the `tidy` options has been the root cause of many a puzzling error for me, so much so that I always turn it off in my setup chunk. I like to control the indenting of my code, as it helps me think better!
