### ISSUE TITLE
problem with strong font

### ISSUE THREAD

**Issue by stla** [ramnathv/poirot#29]
Hello, 

 In the list at the beginning of [this article](http://stla.github.io/stlapblog/posts/KantorovichWithJulia.html), each of the first word (GLPK, JuMP, and RationalSimplex) should be in strong font, but they are not, and I cannot figure out why.

![capture](https://cloud.githubusercontent.com/assets/4466543/2869733/1ad2c17a-d288-11e3-8de6-53d933ba88fa.PNG)

**Comment by ramnathv** [comment]
The trouble is the following line in `custom.css`. The bold fonts used in this Poirot theme have 700 as their weight, and this line overrides it leading to a font-weight that is not available. Easiest fix would be to delete this line from `custom.css`.

``` css
strong, b {
  font-weight: bolder;
}
```

**Comment by stla** [comment]
Right, it works now. Thank you Ramnath.
